package wargame;
import wargame.Sound;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alekspashinin
 */
public class jPanelGamme extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel1
     */
    public jPanelGamme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();

        setBounds(new java.awt.Rectangle(0, 0, 1365, 768));
        setMinimumSize(new java.awt.Dimension(1365, 768));
        setPreferredSize(new java.awt.Dimension(1365, 768));
        setRequestFocusEnabled(false);
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wargame/Images/backjeu.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        jButton111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wargame/Images/menug.png"))); // NOI18N
        jButton111.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton111MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton111MouseExited(evt);
            }
        });
        jButton111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton111ActionPerformed(evt);
            }
        });
        add(jButton111);
        jButton111.setBounds(960, 15, 93, 92);

        jButton112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wargame/Images/turn.png"))); // NOI18N
        jButton112.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton112MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton112MouseExited(evt);
            }
        });
        jButton112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton112ActionPerformed(evt);
            }
        });
        add(jButton112);
        jButton112.setBounds(960, 660, 93, 92);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton111MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton111MouseEntered
        jButton111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wargame/images/menuglight.png")));
        Sound pig = new Sound();
    }//GEN-LAST:event_jButton111MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jButton111MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton111MouseExited
        jButton111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wargame/images/menug.png")));
    }//GEN-LAST:event_jButton111MouseExited

    private void jButton111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton111ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton111ActionPerformed

    private void jButton112MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton112MouseEntered
        jButton112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wargame/images/turnlight.png")));
        Sound pig = new Sound();
    }//GEN-LAST:event_jButton112MouseEntered

    private void jButton112MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton112MouseExited
        jButton112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wargame/images/turn.png")));
    }//GEN-LAST:event_jButton112MouseExited

    private void jButton112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton112ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton112ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
